print("Hello from GitHub on mobile!")
print ("you're awesome, Rae!")
print ("you can do this!")
print ("you are worthy!")
print ("Atta girl!")
print ("We made it through another day!")
print ("Keep going!")
print ("New stuff ahead!")
print ("Ya Rabb!")
print ("Here we go again!")
print ("Things will get better!")
print ("First day of Eid El Adha!")
print ("Second day Eid El Adha! to-do list almost done!")
print ("done packing, reached the bus station early, praying everything goes well!")
print ("birthday weekend! almost done. had a relaxed fun time, elhamdolEllah!")
print ("back from vacation mode!")
print (Arghhhh! those cramps just started!")