print("Hello from GitHub on mobile!")
print ("you're awesome, Rae!")
print ("you can do this!")
print ("you are worthy!")
print ("Atta girl!")
print ("We made it through another day!")
print ("Keep going!")
print ("New stuff ahead!")
print ("Ya Rabb!")
print ("Here we go again!")